### ISSUE TITLE
Problem with associations

### ISSUE THREAD

**Issue by johnfcporto** [anik123/Chat-With-Angularjs-Signalr-Web-Api---Sql-server#2]
Hi there!! I can't run your project. I have these errors:

Error 3 Error 11008: Association 'FK_message_user' is not mapped

Error   4   Error 11008: Association 'FK_online_user' is not mapped

Can you help me?

**Comment by anik123** [comment]
Did you create all tables in database ??

**Comment by johnfcporto** [comment]
No I haven't.. Where do I create the database?

**Comment by anik123** [comment]
I have added database file  'database.sql' in my repository. Please create database in your sql server from that database.sql file.After creating the database change connection string in ChatApi folder's Web.config file.
