### ISSUE TITLE
Problem running

### ISSUE THREAD

**Issue by johnfcporto** [anik123/Chat-With-Angularjs-Signalr-Web-Api---Sql-server#5]
I can't run your project...

i got this error

![image](https://cloud.githubusercontent.com/assets/3793129/11124214/d11f463e-895b-11e5-8e41-3383a3358114.png)

Can you help?

Regards, 

Joao

**Comment by anik123** [comment]
Thanks for your mail.

Kindly Can you provide more information. Like which page is throwing this
error. when this error is throwing ?
ᐧ

Anik Islam Abhi

Software Engineer
Next IT Ltd.
Stackoverflow : http://goo.gl/Fpt1Uv
http://stackoverflow.com/users/4161269/anik-islam-abhi
Linkedin : _https://goo.gl/ldXlgM https://goo.gl/ldXlgM_
Github : https://goo.gl/cyFhTO https://github.com/anik123
